import { randomUUID } from 'node:crypto';
import type { Category, Subcategory, Workspace } from '../types';
import {
  categoryBelongsToWorkspace,
  normalizeRuntimeCategory,
  type PersistedCategory,
} from '../category-ownership';
import {
  instantiateDefaultCategoryTemplate,
  type CategoryTemplateIdFactory,
} from '../default-category-template';
import {
  isSupportedWorkspaceCurrency,
  isWorkspaceCategoryMode,
  WORKSPACE_NAME_MAX_LENGTH,
  type CreateWorkspaceInput,
  type CreateWorkspaceResult,
  type RenameWorkspaceInput,
  type SupportedWorkspaceCurrency,
  type WorkspaceCategoryMode,
} from '../workspace-lifecycle-types';
import { withDataLock } from './data-lock';
import { RestoreError } from './restore-errors';
import {
  getDataManagementPaths,
  recoverPendingRestoresUnlocked,
} from './restore-recovery';
import {
  replaceStoreSetUnlocked,
  type CompleteStoreSet,
  type StoreReplacementTestHooks,
} from './store-replacement';
import { readCompleteStoreSet, validateCompleteStoreSet } from './store-state';

export class WorkspaceLifecycleError extends Error {
  constructor(
    message: string,
    readonly status = 400
  ) {
    super(message);
    this.name = 'WorkspaceLifecycleError';
  }
}

export type WorkspaceLifecycleOptions = {
  dataDirectory?: string;
  operationsDirectory?: string;
  now?: () => Date;
  hooks?: StoreReplacementTestHooks;
  workspaceIdFactory?: () => string;
  categoryIdFactory?: CategoryTemplateIdFactory;
};

type ValidatedCreateInput = {
  name: string;
  baseCurrency: SupportedWorkspaceCurrency;
  categoryMode: WorkspaceCategoryMode;
  sourceWorkspaceId?: string;
};

const generatedCategoryIdFactory: CategoryTemplateIdFactory = {
  categoryId: () => `cat_${randomUUID()}`,
  subcategoryId: () => `sub_${randomUUID()}`,
};

export const normalizeWorkspaceName = (value: unknown): string => {
  if (typeof value !== 'string') {
    throw new WorkspaceLifecycleError('Workspace name is required.');
  }
  const name = value.trim();
  if (!name) throw new WorkspaceLifecycleError('Workspace name is required.');
  if (name.length > WORKSPACE_NAME_MAX_LENGTH) {
    throw new WorkspaceLifecycleError(
      `Workspace name must be ${WORKSPACE_NAME_MAX_LENGTH} characters or fewer.`
    );
  }
  return name;
};

const validateCreateInput = (input: CreateWorkspaceInput): ValidatedCreateInput => {
  if (input && typeof input === 'object' && 'id' in input) {
    throw new WorkspaceLifecycleError('Workspace IDs are generated by FlowLedger.');
  }
  const name = normalizeWorkspaceName(input?.name);
  const baseCurrency = input?.baseCurrency ?? 'EUR';
  if (!isSupportedWorkspaceCurrency(baseCurrency)) {
    throw new WorkspaceLifecycleError('The selected workspace currency is not supported.');
  }
  if (!isWorkspaceCategoryMode(input?.categoryMode)) {
    throw new WorkspaceLifecycleError('The selected starting category set is not supported.');
  }
  if (input.categoryMode === 'copy' && !input.sourceWorkspaceId) {
    throw new WorkspaceLifecycleError('Choose a workspace to copy categories from.');
  }
  return {
    name,
    baseCurrency,
    categoryMode: input.categoryMode,
    sourceWorkspaceId: input.categoryMode === 'copy' ? input.sourceWorkspaceId : undefined,
  };
};

const readCurrentState = (dataDirectory?: string) => {
  try {
    return readCompleteStoreSet(dataDirectory);
  } catch (error) {
    throw new RestoreError(
      'DATA_OPERATION_FAILURE',
      'Workspace data cannot be changed because persisted data is invalid or inconsistent.',
      { cause: error }
    );
  }
};

const toWorkspace = (record: Record<string, unknown>): Workspace => ({
  id: record.id as string,
  ownerUserId: record.ownerUserId as string,
  name: record.name as string,
  baseCurrency: record.baseCurrency as string,
  createdAt: new Date(record.createdAt as string),
  updatedAt: new Date(record.updatedAt as string),
});

const copyCategories = (
  current: CompleteStoreSet,
  sourceWorkspaceId: string,
  targetWorkspaceId: string,
  idFactory: CategoryTemplateIdFactory
): (Category & { subcategories: Subcategory[] })[] => {
  const sourceCategories = current.categories
    .filter((record) => categoryBelongsToWorkspace(record as PersistedCategory, sourceWorkspaceId))
    .map((record) => normalizeRuntimeCategory(record as PersistedCategory));

  return sourceCategories.map((source) => {
    const categoryId = idFactory.categoryId(source.id);
    return {
      id: categoryId,
      workspaceId: targetWorkspaceId,
      name: source.name,
      type: source.type,
      order: source.order,
      isSystem: source.isSystem,
      ...(source.isActive !== undefined ? { isActive: source.isActive } : {}),
      ...(source.isCustom !== undefined ? { isCustom: source.isCustom } : {}),
      subcategories: source.subcategories.map((subcategory) => ({
        id: idFactory.subcategoryId(subcategory.id, source.id),
        workspaceId: targetWorkspaceId,
        categoryId,
        name: subcategory.name,
        order: subcategory.order,
        isSystem: subcategory.isSystem,
        ...(subcategory.isActive !== undefined ? { isActive: subcategory.isActive } : {}),
        ...(subcategory.isCustom !== undefined ? { isCustom: subcategory.isCustom } : {}),
        ...(subcategory.flowType !== undefined ? { flowType: subcategory.flowType } : {}),
      })),
    };
  });
};

const buildInitialCategories = (
  current: CompleteStoreSet,
  input: ValidatedCreateInput,
  workspaceId: string,
  idFactory: CategoryTemplateIdFactory
) => {
  if (input.categoryMode === 'empty') return [];
  if (input.categoryMode === 'default') {
    return instantiateDefaultCategoryTemplate(workspaceId, idFactory);
  }
  if (!current.workspaces.some((workspace) => workspace.id === input.sourceWorkspaceId)) {
    throw new WorkspaceLifecycleError('The source workspace could not be found.', 404);
  }
  return copyCategories(current, input.sourceWorkspaceId!, workspaceId, idFactory);
};

export const createWorkspace = async (
  inputValue: CreateWorkspaceInput,
  ownerUserId: string,
  options: WorkspaceLifecycleOptions = {}
): Promise<CreateWorkspaceResult> => withDataLock(() => {
  const input = validateCreateInput(inputValue);
  if (!ownerUserId) throw new WorkspaceLifecycleError('Workspace owner is required.');

  recoverPendingRestoresUnlocked(options);
  const current = readCurrentState(options.dataDirectory);
  const workspaceId = (options.workspaceIdFactory ?? (() => `ws_${randomUUID()}`))();
  if (!workspaceId || current.workspaces.some((workspace) => workspace.id === workspaceId)) {
    throw new WorkspaceLifecycleError('A globally unique workspace ID could not be generated.', 409);
  }

  const timestamp = (options.now ?? (() => new Date()))().toISOString();
  const workspaceRecord = {
    id: workspaceId,
    ownerUserId,
    name: input.name,
    baseCurrency: input.baseCurrency,
    createdAt: timestamp,
    updatedAt: timestamp,
  };
  const initialCategories = buildInitialCategories(
    current,
    input,
    workspaceId,
    options.categoryIdFactory ?? generatedCategoryIdFactory
  );
  const resulting = structuredClone(current) as CompleteStoreSet;
  resulting.workspaces.push(workspaceRecord);
  resulting.categories.push(...initialCategories);
  validateCompleteStoreSet(resulting);

  const replacement = replaceStoreSetUnlocked(
    resulting,
    getDataManagementPaths(options),
    {
      operationKind: 'workspace-create',
      targetStores: ['workspaces', 'categories'],
      now: options.now,
      hooks: options.hooks,
      executionFailureCode: 'DATA_OPERATION_FAILURE',
      preparationFailureMessage: 'Workspace creation could not be prepared. Current data was not changed.',
      rollbackSuccessMessage: 'Workspace creation failed. Original data was restored successfully.',
      cleanupWarningMessage: 'The workspace was created, but temporary recovery files could not be fully removed.',
    }
  );

  return {
    workspace: toWorkspace(workspaceRecord),
    categoryCount: initialCategories.length,
    cleanupWarning: replacement.cleanupWarning,
  };
});

export const renameWorkspace = async (
  inputValue: RenameWorkspaceInput,
  ownerUserId: string,
  options: WorkspaceLifecycleOptions = {}
): Promise<Workspace> => withDataLock(() => {
  const workspaceId = typeof inputValue?.workspaceId === 'string'
    ? inputValue.workspaceId.trim()
    : '';
  if (!workspaceId) throw new WorkspaceLifecycleError('Workspace ID is required.');
  const name = normalizeWorkspaceName(inputValue?.name);

  recoverPendingRestoresUnlocked(options);
  const current = readCurrentState(options.dataDirectory);
  const index = current.workspaces.findIndex((workspace) => workspace.id === workspaceId);
  const existing = current.workspaces[index];
  if (!existing || existing.ownerUserId !== ownerUserId) {
    throw new WorkspaceLifecycleError('Workspace not found.', 404);
  }

  const timestamp = (options.now ?? (() => new Date()))().toISOString();
  const updated = { ...existing, name, updatedAt: timestamp };
  const resulting = structuredClone(current) as CompleteStoreSet;
  resulting.workspaces[index] = updated;
  validateCompleteStoreSet(resulting);

  replaceStoreSetUnlocked(resulting, getDataManagementPaths(options), {
    operationKind: 'workspace-rename',
    targetStores: ['workspaces'],
    now: options.now,
    hooks: options.hooks,
    executionFailureCode: 'DATA_OPERATION_FAILURE',
    preparationFailureMessage: 'Workspace rename could not be prepared. Current data was not changed.',
    rollbackSuccessMessage: 'Workspace rename failed. Original data was restored successfully.',
    cleanupWarningMessage: 'The workspace was renamed, but temporary recovery files could not be fully removed.',
  });

  return toWorkspace(updated);
});
